### ISSUE TITLE
update to .netcore 2.0

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [bmaluijb/Dot-Net-Ecosystem#1]
Hi, 

Right now .netcore 2.0 is out. It's not exactly the same as .netcore 1.1 and I have difficulty in configuring it. Is it possible to update the app using .netcore 2?

Thanks.

**Comment by bmaluijb** [comment]
Sure can. I will do that as soon as I get the chance.

**Comment by bmaluijb** [comment]
Just pushed an update where I updated the .NET Core applications and the .NET Standard library to 2.0. Thanks for creating the issue!

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you.
